version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/registrafirma
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER:redis://redis:6379/0
      - CELERY_BACKEND:redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:5.0.1
    command: redis-server
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A registrafirma worker -l info --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/registrafirma
    depends_on:
      - web
      - redis
