# Generated by Django 4.2.10 on 2024-02-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_created_at_alter_company_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('nonexistent', 'Nonexistent')], default='active', max_length=11, verbose_name='Status'),
        ),
    ]
