# Generated by Django 4.2.10 on 2024-02-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
    ]
